# Generated by Django 3.0.4 on 2020-03-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200312_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enabled',
        ),
    ]
