# Generated by Django 3.0.4 on 2020-03-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200312_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
