# Generated by Django 3.0.4 on 2020-03-13 08:57

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200313_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=apps.accounts.models.NullableEmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='e-mail address'),
        ),
    ]
