# Generated by Django 3.0.4 on 2020-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200313_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='asset\\placeholder-profile.jpg', upload_to='profile\\photo'),
        ),
    ]
